name: deploy in vps
on:
    push:
        branches:
            - main
            - deploy
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: |
                echo ${{ secrets.PASSWORD }}
                echo ${{ secrets.HOST }}
                echo ${{ secrets.USERNAME }}
                echo ${{ secrets.SSH_KEY }}
            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  source: "../../../Anchor_upload_automation"
                  port: ${{ secrets.PORT }}
                  target: "/home/herika"