name: deploy in vps
on:
    push:
        branches:
            - main
            - deploy
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Deploy
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  PORT: ${{ secrets.PORT }}
              with:
                  source: "."
                  target: "~/home/herika"
                  script: |
                      cd ~/home/herika
                      git pull origin deploy 
             - name: Executing remote command